# Secret for PostgreSQL credentials
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: zeta-guard
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: "zeta-guard"
  POSTGRES_PASSWORD: "geheim"
  POSTGRES_DB: "keycloak"

---
# Secret for Keycloak credentials
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: zeta-guard
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: "zeta"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "sigma"
