# Secret for PostgreSQL credentials
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: "{{ .Values.namespace }}"
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.secrets.postgres.admin.name }}"
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgres.admin.password }}"
  POSTGRES_DB: "{{ .Values.deployments.postgres.db.name }}"

---
# Secret for Keycloak credentials
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: "{{ .Values.namespace }}"
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME:  "{{ .Values.secrets.keycloak.admin.name }}"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "{{ .Values.secrets.keycloak.admin.password }}"
